# Generated by Django 5.2.5 on 2025-08-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ParagraphWordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('count', models.PositiveIntegerField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_frequencies', to='app.paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('total_count', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_frequencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='paragraph',
            index=models.Index(fields=['user', 'index'], name='app_paragra_user_id_6022ff_idx'),
        ),
        migrations.AddIndex(
            model_name='paragraphwordfrequency',
            index=models.Index(fields=['word'], name='app_paragra_word_c0bf58_idx'),
        ),
        migrations.AddIndex(
            model_name='paragraphwordfrequency',
            index=models.Index(fields=['paragraph', 'word'], name='app_paragra_paragra_2373d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paragraphwordfrequency',
            unique_together={('paragraph', 'word')},
        ),
        migrations.AddIndex(
            model_name='wordfrequency',
            index=models.Index(fields=['user', 'word'], name='app_wordfre_user_id_25175d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordfrequency',
            unique_together={('user', 'word')},
        ),
    ]
